language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kra5io/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kra5io/react-test npm run test 

after_success:
  - docker build -t kra5io/multi-client ./client
  - docker build -t kra5io/multi-nginx ./nginx
  - docker build -t kra5io/multi-server ./server
  - docker build -t kra5io/multi-worker ./worker
  # Log in to the docker CLI
  - echo "#DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push kra5io/multi-client
  - docker push kra5io/multi-nginx
  - docker push kra5io/multi-server
  - docker push kra5io/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY